version: 2
jobs:
   build:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: latexmk constitution.tex
       - run: pdflatex constitution.tex
       - store_artifacts:
           path: constitution.pdf
